# coding: utf-8

"""
    Pose Transform

    API server for PoseTransformGAN  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ttakamura@preferred.jp
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.poses import Poses  # noqa: E501
from swagger_client.rest import ApiException


class TestPoses(unittest.TestCase):
    """Poses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPoses(self):
        """Test Poses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.poses.Poses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
