# coding: utf-8

"""
    Pose Transform

    API server for PoseTransformGAN  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ttakamura@preferred.jp
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.puppet_api import PuppetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPuppetApi(unittest.TestCase):
    """PuppetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.puppet_api.PuppetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_puppet(self):
        """Test case for create_puppet

        Create new Puppet model  # noqa: E501
        """
        pass

    def test_draw(self):
        """Test case for draw

        Draw new image based on the Puppet and input pose  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
