# coding: utf-8

# flake8: noqa
"""
    Pose Transform

    API server for PoseTransformGAN  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ttakamura@preferred.jp
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.bone import Bone
from swagger_client.models.joint import Joint
from swagger_client.models.pose import Pose
from swagger_client.models.poses import Poses
from swagger_client.models.puppet import Puppet
